import { useEffect, useState } from "react";
import type { AppRecord, Profile } from "@pyro/contracts";
import { api } from "@/lib/api";
import { PageHeader } from "@/components/shared";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
interface Dataset { id: string; name: string; version: number; count: number; appId: string; contentHash: string; expiresAt: string }
interface Stats { count: number; accuracy: number | null; falsePositiveRate: number | null; indeterminate: number; p50LatencyMs: number | null; p95LatencyMs: number | null; reportedCosts: Record<string, number>; costUnreported: number; confusion: Record<string, Record<string, number>> }
interface Run { id: string; status: string; total: number; datasetHash: string; configurationHash: string; createdAt: string; error?: string; rows?: unknown[]; report?: { policies: Record<string, Stats>; disagreements: unknown[]; changedCases: string[] }; estimate: { maximumProviderCalls: number; cost: string } }
const selectStyle = "border border-line bg-surface p-2 text-sm";
export function EvaluationsPage({ canRun }: { canRun: boolean }) {
  const [datasets, setDatasets] = useState<Dataset[]>([]), [runs, setRuns] = useState<Run[]>([]), [apps, setApps] = useState<AppRecord[]>([]), [profiles, setProfiles] = useState<Profile[]>([]);
  const [appId, setAppId] = useState(""), [name, setName] = useState(""), [jsonl, setJsonl] = useState(""), [retention, setRetention] = useState(7), [retain, setRetain] = useState(false);
  const [datasetId, setDatasetId] = useState(""), [first, setFirst] = useState(""), [second, setSecond] = useState(""), [revision, setRevision] = useState(1), [otherRevision, setOtherRevision] = useState(1), [paid, setPaid] = useState(false);
  const [selected, setSelected] = useState<Run>(), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const load = async () => { const [d, r, a, p] = await Promise.all([api.get<{ datasets: Dataset[] }>("/api/datasets"), api.get<{ runs: Run[] }>("/api/evaluations"), api.get<{ apps: AppRecord[] }>("/api/apps"), api.get<{ profiles: Profile[] }>("/api/profiles")]); setDatasets(d.datasets); setRuns(r.runs); setApps(a.apps); setProfiles(p.profiles); setAppId((id) => id || a.apps[0]?.id || ""); setDatasetId((id) => id || d.datasets[0]?.id || ""); };
  const inspect = async (id: string) => { const { run } = await api.get<{ run: Run }>(`/api/evaluations/${id}`); setSelected(run); };
  useEffect(() => { void load().catch((e) => setMessage(e.message)); }, []);
  useEffect(() => { if (!selected || !["queued", "running"].includes(selected.status)) return; const timer = setInterval(() => void inspect(selected.id).catch((e) => setMessage(e.message)), 1500); return () => clearInterval(timer); }, [selected?.id, selected?.status]);
  const work = async (fn: () => Promise<unknown>) => { setBusy(true); setMessage(""); try { await fn(); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Request failed."); } finally { setBusy(false); } };
  const changeProfile = (id: string, other = false) => { const rev = profiles.find((p) => p.id === id)?.revision ?? 1; if (other) { setSecond(id); setOtherRevision(rev); } else { setFirst(id); setRevision(rev); } };
  const dataset = datasets.find((d) => d.id === datasetId);
  const semantic = [first, second].some((id) => profiles.find((p) => p.id === id)?.detectors.some((d) => d.enabled));
  const download = () => { const url = URL.createObjectURL(new Blob([JSON.stringify(selected, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `pyro-evaluation-${selected!.id}.json`; link.click(); URL.revokeObjectURL(url); };
  const percent = (v: number | null) => v === null ? "—" : `${(v * 100).toFixed(1)}%`;
  return <div className="space-y-6"><PageHeader title="Evaluation lab" description="Compare published policy revisions on a versioned dataset using the same classification engine as the gateway. Results describe this dataset, not general protection coverage." />
    {message && <p role="status" className="border border-line p-3 text-sm">{message}</p>}
    {canRun && <Card><CardContent className="space-y-4 p-5"><h2 className="font-semibold">Import a dataset version</h2><div className="flex flex-wrap gap-4"><label>Application<select className={`ml-2 ${selectStyle}`} value={appId} onChange={(e) => setAppId(e.target.value)}>{apps.map((a) => <option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>Name<Input value={name} onChange={(e) => setName(e.target.value)} /></label></div><p className="text-sm text-muted">JSONL: one object per line with id, input, expected (allow / review / block), and optional category. Maximum 500 cases. Reimport the same name to create a new version.</p><input aria-label="Import JSONL file" type="file" accept=".jsonl,.ndjson,.json" onChange={(e) => { const file = e.target.files?.[0]; if (file) void file.text().then(setJsonl).catch((e) => setMessage(e.message)); }} /><Textarea aria-label="JSONL dataset" className="min-h-36 font-mono text-xs" value={jsonl} onChange={(e) => setJsonl(e.target.value)} placeholder={'{"id":"benign-1","input":"Hello","expected":"allow","category":"benign"}'} /><label>Retention<select className={`ml-2 ${selectStyle}`} value={retention} onChange={(e) => setRetention(Number(e.target.value))}>{[1, 7, 30].map((n) => <option value={n} key={n}>{n} days</option>)}</select></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={retain} onChange={(e) => setRetain(e.target.checked)} />Retain these redacted inputs encrypted in this deployment for the selected period.</label><Button disabled={busy || !retain || !jsonl.trim() || !name.trim()} onClick={() => void work(async () => { const result = await api.post<{ dataset: Dataset }>("/api/datasets", { appId, name, jsonl, retentionDays: retention, retainInputs: retain }); setDatasetId(result.dataset.id); setJsonl(""); setRetain(false); setMessage(`Dataset version ${result.dataset.version} saved.`); })}>Import version</Button></CardContent></Card>}
    {canRun && <Card><CardContent className="space-y-4 p-5"><h2 className="font-semibold">Compare policies</h2><label className="block">Dataset<select className={`ml-2 ${selectStyle}`} value={datasetId} onChange={(e) => setDatasetId(e.target.value)}><option value="">Choose dataset</option>{datasets.map((d) => <option key={d.id} value={d.id}>{d.name} v{d.version} · {d.count} cases · {d.appId}</option>)}</select></label>{dataset && <p className="break-all text-xs text-muted">Hash {dataset.contentHash} · expires {new Date(dataset.expiresAt).toLocaleString()}</p>}
      <div className="flex flex-wrap gap-4">{[false, true].map((other) => <div className="flex items-end gap-2" key={String(other)}><label>{other ? "Compare with (optional)" : "Baseline"}<select className={`block ${selectStyle}`} value={other ? second : first} onChange={(e) => changeProfile(e.target.value, other)}><option value="">Choose policy</option>{profiles.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="w-24">Revision<Input type="number" min={1} value={other ? otherRevision : revision} onChange={(e) => other ? setOtherRevision(Number(e.target.value)) : setRevision(Number(e.target.value))} /></label></div>)}</div>
      <p className="text-sm text-muted">{semantic ? `Semantic policies send inputs to TypeSafe unless this deployment uses mock mode. Up to ${(dataset?.count ?? 0) * (second ? 2 : 1) * 6} attempts including retries; actual retries may be lower. Price is unknown. Check provider billing before starting.` : "Local-only policies make no provider calls. Earlier revisions may differ: the server will require confirmation for any semantic run."}</p><label className="flex gap-2 text-sm"><input type="checkbox" checked={paid} onChange={(e) => setPaid(e.target.checked)} />I authorize this dataset to be sent to the configured semantic provider and accept its charges, if these revisions use it.</label><div className="flex flex-wrap gap-3"><Button disabled={busy || !datasetId || !first} onClick={() => void work(async () => { const policies = [{ id: first, revision }, ...(second ? [{ id: second, revision: otherRevision }] : [])]; const result = await api.post<{ run: Run }>("/api/evaluations", { datasetId, policies, allowPaid: paid }); setSelected(result.run); })}>Run evaluation</Button><Button variant="outline" disabled={busy || !datasetId} onClick={() => void work(async () => { await api.delete(`/api/datasets/${datasetId}`); setDatasetId(""); setMessage("Dataset inputs deleted. Active runs were cancelled."); })}>Delete dataset inputs</Button></div></CardContent></Card>}
    <Card><CardContent className="space-y-3 p-5"><h2 className="font-semibold">Runs</h2>{[...runs].reverse().map((r) => <button className="block w-full border-b border-line py-2 text-left text-sm" key={r.id} onClick={() => void inspect(r.id).catch((e) => setMessage(e.message))}>{new Date(r.createdAt).toLocaleString()} · {r.status} · {r.id.slice(0, 8)}</button>)}{!runs.length && <p className="text-sm text-muted">No runs yet.</p>}</CardContent></Card>
    {selected && <Card><CardContent className="space-y-4 overflow-auto p-5"><h2 className="font-semibold">{selected.status} · {selected.rows?.length ?? 0}/{selected.total} comparisons</h2><p className="text-sm text-muted">{selected.estimate.cost} Maximum provider attempts: {selected.estimate.maximumProviderCalls}. A cancellation stops between calls; an in-flight call can still be billed.</p>{selected.error && <p role="alert">{selected.error}</p>}<p className="break-all text-xs text-muted">Dataset {selected.datasetHash}<br />Configuration {selected.configurationHash}</p><div className="flex gap-3"><Button variant="outline" onClick={download}>Download report</Button>{canRun && selected.status !== "complete" && <Button variant="outline" disabled={busy} onClick={() => void work(async () => { const action = ["cancelled", "failed"].includes(selected.status) ? "resume" : "cancel"; await api.put(`/api/evaluations/${selected.id}`, { action }); await inspect(selected.id); })}>{["cancelled", "failed"].includes(selected.status) ? "Resume" : "Cancel"}</Button>}</div>
      {selected.report && <><table className="w-full text-left text-sm"><thead><tr><th>Policy</th><th>Cases</th><th>Accuracy</th><th>False positives</th><th>Indeterminate</th><th>p50 / p95 ms</th><th>Reported cost</th></tr></thead><tbody>{Object.entries(selected.report.policies).map(([key, s]) => <tr key={key} className="border-t border-line"><td className="py-3">{key}</td><td>{s.count}</td><td>{percent(s.accuracy)}</td><td>{percent(s.falsePositiveRate)}</td><td>{s.indeterminate}</td><td>{s.p50LatencyMs?.toFixed(1)} / {s.p95LatencyMs?.toFixed(1)}</td><td>{Object.entries(s.reportedCosts).map(([currency, amount]) => `${currency} ${amount}`).join(", ") || "Unknown"}{s.costUnreported ? ` (${s.costUnreported} unreported)` : ""}</td></tr>)}</tbody></table><p className="text-sm">{selected.report.disagreements.length} disagreements with expected outcomes · {selected.report.changedCases.length} cases changed between policies.</p><details><summary>Confusion matrices and disagreements</summary><pre className="mt-3 overflow-auto text-xs">{JSON.stringify(selected.report, null, 2)}</pre></details></>}
    </CardContent></Card>}
  </div>;
}
