import { useEffect, useState } from "react";
import type { UserRecord } from "@pyro/contracts";
import { api, selectOrganization } from "@/lib/api";
import type { Organization } from "@/lib/cloud";
import { PageHeader } from "@/components/shared";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
interface Billing { eventStorage?: { usedBytes: number; limitBytes: number }; balance: number; consumed: number; unit: string; checkoutAvailable: boolean; pack: { credits: number; amount: number; currency: string }; entries: Array<{ id: string; kind: string; credits: number; at: number }> }
export function OrganizationPage({ user, organization, onChanged }: { user: UserRecord; organization?: Organization; onChanged: () => Promise<void> }) {
  const [name, setName] = useState(organization?.name ?? ""); const [newName, setNewName] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const [billing, setBilling] = useState<Billing>(); const [members, setMembers] = useState<UserRecord[]>([]); const [nextOwner, setNextOwner] = useState("");
  const [confirmation, setConfirmation] = useState(""); const [deleting, setDeleting] = useState(false);
  const owner = user.organizationRole === "owner", admin = owner || user.organizationRole === "admin";
  const load = async () => { if (!organization || !admin) return; const [bill, team] = await Promise.all([api.get<Billing>("/api/billing"), api.get<{ users: UserRecord[] }>("/api/team")]); setBilling(bill); setMembers(team.users); };
  useEffect(() => { void load().catch((e) => setMessage(e.message)); }, [organization?.id]);
  const run = async (work: () => Promise<void>) => { setBusy(true); setMessage(""); try { await work(); } catch (error) { setMessage(error instanceof Error ? error.message : "Please try again."); } finally { setBusy(false); } };
  const create = () => run(async () => { const result = await api.post<{ organization: Organization }>("/api/organizations", { name: newName }); selectOrganization(result.organization.id); await onChanged(); });
  const buy = () => run(async () => {
    const order = await api.post<{ id: string; amount: number; currency: string; key: string }>("/api/billing/order");
    if (!window.Razorpay) await new Promise<void>((resolve, reject) => { const script = document.createElement("script"); script.src = "https://checkout.razorpay.com/v1/checkout.js"; script.onload = () => resolve(); script.onerror = () => reject(new Error("Could not load checkout.")); document.head.append(script); });
    new window.Razorpay!({ key: order.key, order_id: order.id, amount: order.amount, currency: order.currency, name: "Pyro", description: "Prepaid policy credits", handler: () => { setMessage("Payment submitted. Credits appear after the payment provider confirms capture. Refresh to check."); void load(); } }).open();
  });
  return <>
    <PageHeader title={organization ? "Organization & billing" : "Create your organization"} />
    {message && <p role="status" className="mb-5 rounded-control border border-line bg-surface-subtle p-3 text-sm">{message}</p>}
    <div className="max-w-4xl space-y-5">
      {organization && <Card><CardHeader><CardTitle>{organization.name}</CardTitle><CardDescription><Badge>{user.organizationRole}</Badge></CardDescription></CardHeader><CardContent className="space-y-4">
        <div className="space-y-2"><Label htmlFor="organization-name">Organization name</Label><Input id="organization-name" value={name} disabled={!owner || busy} maxLength={100} onChange={(e) => setName(e.target.value)} /></div>
        {owner && <Button disabled={busy || name.trim().length < 2} onClick={() => void run(async () => { await api.put("/api/organizations/current", { name }); await onChanged(); setMessage("Organization updated."); })}>Save name</Button>}
        <p className="text-xs text-muted">Semantic checks send input to the configured classifier provider. Input previews are off by default; datasets retain inputs only with explicit consent.</p>
      </CardContent></Card>}
      {organization && admin && <Card><CardHeader><CardTitle>Prepaid credits</CardTitle><CardDescription>Usage stops when credits run out. There are no automatic overage charges.</CardDescription></CardHeader><CardContent className="space-y-4">
        {billing ? <><div className="grid gap-4 sm:grid-cols-2"><div><p className="text-sm text-muted">Available credits</p><p className="mt-1 text-3xl font-semibold">{billing.balance.toLocaleString()}</p></div><div><p className="text-sm text-muted">Consumed credits</p><p className="mt-1 text-3xl font-semibold">{billing.consumed.toLocaleString()}</p></div></div><p className="text-sm leading-6 text-muted">{billing.unit}</p>{billing.eventStorage && <p className="text-xs text-muted">Event storage this month: {(billing.eventStorage.usedBytes / 1_000_000).toFixed(1)} / {billing.eventStorage.limitBytes / 1_000_000} MB. A shared platform allowance also applies.</p>}<div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={() => void run(load)}>Refresh balance</Button>{owner && <Button disabled={busy || !billing.checkoutAvailable} onClick={() => void buy()}>Buy {billing.pack.credits.toLocaleString()} credits · ₹{(billing.pack.amount / 100).toLocaleString()}</Button>}</div>{!billing.checkoutAvailable && <p className="text-xs text-muted">Online payments are not enabled for this deployment. Contact the operator to arrange prepaid credits.</p>}
        {billing.entries.length > 0 && <Table><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Type</TableHead><TableHead className="text-right">Credits</TableHead></TableRow></TableHeader><TableBody>{billing.entries.map((entry) => <TableRow key={entry.id}><TableCell className="whitespace-nowrap">{new Date(entry.at).toLocaleString()}</TableCell><TableCell>{entry.kind}</TableCell><TableCell className="text-right">{entry.credits > 0 ? "+" : ""}{entry.credits}</TableCell></TableRow>)}</TableBody></Table>}</> : <p role="status" className="text-sm text-muted">Loading billing…</p>}
      </CardContent></Card>}
      <Card><CardHeader><CardTitle>{organization ? "New organization" : "New organization"}</CardTitle><CardDescription>Each organization has separate policies, access and credits.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label htmlFor="new-organization">Organization name</Label><Input id="new-organization" value={newName} maxLength={100} onChange={(e) => setNewName(e.target.value)} placeholder="Your company or project" /></div><Button disabled={busy || newName.trim().length < 2} onClick={() => void create()}>{busy ? "Creating…" : "Create organization"}</Button></CardContent></Card>
      {organization && owner && <Card><CardHeader><CardTitle>Ownership and data</CardTitle></CardHeader><CardContent className="space-y-5">
        <div className="space-y-2"><Label htmlFor="next-owner">Transfer ownership to a member</Label><Select value={nextOwner} onValueChange={setNextOwner}><SelectTrigger id="next-owner"><SelectValue placeholder="Choose an active member" /></SelectTrigger><SelectContent>{members.filter((m) => m.id !== user.id && !m.disabled).map((m) => <SelectItem key={m.id} value={m.id}>{m.username}</SelectItem>)}</SelectContent></Select><p className="text-xs text-muted">You will become an administrator after transfer.</p></div><Button variant="outline" disabled={busy || !nextOwner} onClick={() => void run(async () => { await api.post("/api/organizations/transfer", { userId: nextOwner }); await onChanged(); })}>Transfer ownership</Button>
        <div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={() => void run(async () => { const first = await api.get<{ events: unknown[]; totalEvents: number; pageSize: number }>("/api/organizations/export"); for (let offset = first.events.length; offset < first.totalEvents; offset += first.pageSize) { const page = await api.get<typeof first>(`/api/organizations/export?offset=${offset}`); first.events.push(...page.events); } const url = URL.createObjectURL(new Blob([JSON.stringify(first, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "pyro-organization.json"; link.click(); URL.revokeObjectURL(url); })}>Export organization</Button><Button variant="outline" className="text-danger" disabled={busy} onClick={() => { setMessage(""); setDeleting(true); }}>Delete organization</Button></div>
      </CardContent></Card>}
    </div>
    <Dialog open={deleting} onOpenChange={(open) => { if (!busy) setDeleting(open); }}><DialogContent><DialogHeader><DialogTitle>Delete organization</DialogTitle><DialogDescription>Policies, keys, activity and retained inputs will be erased. Payment records and expiring backups follow their retention policy. Enter “{organization?.name}” to confirm.</DialogDescription></DialogHeader><div className="space-y-2 px-6 py-5"><Label htmlFor="delete-confirmation">Organization name</Label><Input id="delete-confirmation" value={confirmation} onChange={(e) => setConfirmation(e.target.value)} />{message && <p role="alert" className="text-sm text-danger">{message}</p>}</div><DialogFooter><Button variant="outline" disabled={busy} onClick={() => setDeleting(false)}>Cancel</Button><Button disabled={busy || confirmation !== organization?.name} onClick={() => void run(async () => { await api.delete("/api/organizations/current", { confirmation }); selectOrganization(undefined); await onChanged(); setDeleting(false); })}>Delete permanently</Button></DialogFooter></DialogContent></Dialog>
  </>;
}
declare global { interface Window { Razorpay?: new (options: Record<string, unknown>) => { open(): void } } }
