import { useEffect, useState } from "react";
import type { ClassificationEvent } from "@pyro/contracts";
import { api } from "@/lib/api";
import { PageHeader } from "@/components/shared";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
interface Review { id: string; revision: number; status: string; appId: string; assignedTo?: string; severity: string; disposition?: string; ageMs: number; comments: Array<{ id: string; actorId: string; at: string; text: string }>; event: ClassificationEvent }
export function ReviewsPage({ canReview }: { canReview: boolean }) {
  const [reviews, setReviews] = useState<Review[]>([]); const [assignees, setAssignees] = useState<Array<{ id: string; username: string }>>([]);
  const [selected, setSelected] = useState(""); const [status, setStatus] = useState(() => localStorage.getItem("pyro-review-filter") || "open");
  const [comment, setComment] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [sample, setSample] = useState(""); const [expected, setExpected] = useState("allow");
  const [offset, setOffset] = useState(0); const [nextOffset, setNextOffset] = useState<number | null>(null);
  const load = async () => { const result = await api.get<{ reviews: Review[]; assignees: typeof assignees; nextOffset: number | null }>(`/api/reviews?status=${status}&offset=${offset}`); setReviews(result.reviews); setAssignees(result.assignees); setNextOffset(result.nextOffset); };
  useEffect(() => { void load().catch((e) => setMessage(e.message)); localStorage.setItem("pyro-review-filter", status); }, [status, offset]);
  const current = reviews.find((r) => r.id === selected);
  const save = async (changes: Record<string, unknown>) => { if (!current) return; setBusy(true); setMessage(""); try { await api.put(`/api/reviews/${current.id}`, { expectedRevision: current.revision, ...changes }); setComment(""); await load(); setMessage("Review saved. The original decision is unchanged."); } catch (e) { setMessage(e instanceof Error ? e.message : "Save failed."); } finally { setBusy(false); } };
  const exportSample = () => { const blob = new Blob([JSON.stringify({ id: current!.id, input: sample, expected, category: "review-feedback" }) + "\n"], { type: "application/x-ndjson" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "review-sample.jsonl"; link.click(); URL.revokeObjectURL(url); };
  return <div className="space-y-6"><PageHeader title="Review inbox" description="Assign and resolve review decisions. Feedback never executes a tool or changes the original enforcement result." />
    <div className="flex gap-3"><label>Status <select className="ml-2 border border-line bg-surface p-2" value={status} onChange={(e) => { setStatus(e.target.value); setOffset(0); }}>{["open", "resolved", ""].map((s) => <option key={s} value={s}>{s || "All"}</option>)}</select></label><Button variant="outline" onClick={() => void load().catch((e) => setMessage(e.message))}>Refresh</Button></div>
    {message && <p role="status" className="border border-line p-3 text-sm">{message}</p>}
    <Card><CardContent className="overflow-auto p-4"><table className="w-full text-left text-sm"><thead><tr><th>Decision</th><th>Application / trace</th><th>Severity</th><th>Age</th><th>Status</th></tr></thead><tbody>{reviews.map((r) => <tr className="border-t border-line" key={r.id}><td className="max-w-xs py-3"><button className="text-left underline" onClick={() => { setSelected(r.id); setSample(r.event.inputPreview ?? ""); setComment(""); }}>{r.event.reason}</button></td><td>{r.appId}<br /><code className="text-xs">{r.event.traceId?.slice(0, 12) ?? r.event.requestId?.slice(0, 12)}</code></td><td>{r.severity}</td><td>{Math.floor(r.ageMs / 60000)} min</td><td>{r.disposition ?? r.status}</td></tr>)}</tbody></table>{!reviews.length && <p className="py-6 text-muted">No matching reviews on this page.</p>}<div className="mt-4 flex gap-2"><Button variant="outline" disabled={!offset} onClick={() => setOffset(Math.max(0, offset - 500))}>Previous</Button><Button variant="outline" disabled={nextOffset === null} onClick={() => setOffset(nextOffset!)}>Next</Button></div></CardContent></Card>
    {current && <Card><CardContent className="space-y-4 p-5"><h2 className="font-semibold">Review {current.id}</h2><p className="text-sm text-muted">Policy {current.event.profileId} · revision {current.event.policyRevision ?? "legacy"} · original action {current.event.action}</p>
      {canReview && <div className="flex flex-wrap gap-4"><label>Assignee<select disabled={busy} className="ml-2 border border-line bg-surface p-2" value={current.assignedTo ?? ""} onChange={(e) => void save({ assignedTo: e.target.value || null })}><option value="">Unassigned</option>{assignees.map((u) => <option key={u.id} value={u.id}>{u.username}</option>)}</select></label><label>Severity<select disabled={busy} className="ml-2 border border-line bg-surface p-2" value={current.severity} onChange={(e) => void save({ severity: e.target.value })}>{["low", "medium", "high"].map((s) => <option key={s}>{s}</option>)}</select></label></div>}
      <div className="space-y-3">{current.comments.map((c) => <div key={c.id} className="border-l-2 border-line pl-3"><p className="text-xs text-muted">{c.actorId} · {new Date(c.at).toLocaleString()}</p><p className="whitespace-pre-wrap text-sm">{c.text}</p></div>)}</div>
      {canReview && <><label className="block">Comment<Textarea maxLength={2000} value={comment} onChange={(e) => setComment(e.target.value)} /></label><Button disabled={busy || !comment.trim()} onClick={() => void save({ comment })}>Add comment</Button><div className="flex flex-wrap gap-2">{["true_positive", "false_positive", "uncertain"].map((d) => <Button key={d} variant="outline" disabled={busy} onClick={() => void save({ disposition: d, ...(comment.trim() ? { comment } : {}) })}>{d.replaceAll("_", " ")}</Button>)}{current.status === "resolved" && <Button variant="outline" disabled={busy} onClick={() => void save({ reopen: true })}>Reopen</Button>}</div></>}
      {canReview && <div className="space-y-3 border-t border-line pt-4"><h3 className="font-semibold">Create an evaluation sample</h3><p className="text-sm text-muted">Enter a redacted, complete example. A stored preview may be truncated. Export downloads a local file for explicit import into the evaluation lab.</p><Textarea aria-label="Redacted evaluation input" value={sample} onChange={(e) => setSample(e.target.value)} /><label>Expected action<select className="ml-3 border border-line bg-surface p-2" value={expected} onChange={(e) => setExpected(e.target.value)}>{["allow", "review", "block"].map((s) => <option key={s}>{s}</option>)}</select></label><Button variant="outline" disabled={!sample.trim()} onClick={exportSample}>Download JSONL sample</Button></div>}
    </CardContent></Card>}
  </div>;
}
