import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";
import { buildGateway } from "../../../apps/gateway/src/app.js";
import { buildControlPlane } from "../../../apps/control-plane/src/app.js";
import { invoke, temporary } from "./helpers.js";

test("CLI workflow against real gateway and dashboard APIs with isolated in-memory storage", async t => {
  const directory = await temporary(t), config = join(directory, "config.json");
  const databaseUrl = `memory://cli-${randomUUID()}`, key = "pf_cli_integration_test", secret = "cli-integration-test-secret-at-least-32";
  const gateway = await buildGateway({ host: "127.0.0.1", port: 0, databaseUrl, queueConcurrency: 2, queueMaxDepth: 10, defaultTimeoutMs: 1_000, controlPlaneSecret: secret, bootstrapApiKey: key });
  const gatewayUrl = await gateway.listen({ host: "127.0.0.1", port: 0 });
  t.after(() => gateway.close());
  const control = await buildControlPlane({ host: "127.0.0.1", port: 0, databaseUrl, adminPassword: "cli-test-password", controlPlaneSecret: secret, gatewayInternalUrl: gatewayUrl, gatewayApiKey: key, typesafeEndpoint: "https://api.typesafe.ai/v1/systemone", typesafeModel: "jev-latest" });
  const controlUrl = await control.listen({ host: "127.0.0.1", port: 0 });
  t.after(() => control.close());
  const run = (args: string[], input?: string, apiKey = key) => invoke(["--gateway-url", gatewayUrl, "--control-url", controlUrl, ...args], { config, input, env: { PYRO_API_KEY: apiKey } });
  const json = async (args: string[], input?: string, apiKey = key) => {
    const result = await run(args, input, apiKey);
    assert.equal(result.code, 0, `${args.join(" ")}: ${result.stderr}`);
    return JSON.parse(result.stdout);
  };
  assert.equal((await run(["profiles", "list"])).code, 3);
  await json(["auth", "login", "--password-stdin"], "cli-test-password\n");
  assert.equal((await json(["auth", "status"])).user.username, "admin");
  assert.equal((await json(["health"])).status, "ok");
  assert.ok((await json(["profiles", "list"])).profiles.some((profile: { id: string }) => profile.id === "default"));
  const presets = await json(["profiles", "presets"]);
  const yaml = presets.presets.find((preset: { profile: { id: string } }) => preset.profile.id === "local-secrets").yaml;
  const preview = await json(["profiles", "preview", "--file", "-"], yaml);
  assert.equal(preview.profile.id, "local-secrets");
  const file = join(directory, "profile.yaml"); await writeFile(file, yaml);
  assert.equal((await json(["profiles", "import", "--file", file])).profile.id, "local-secrets");
  assert.equal((await run(["profiles", "import", "--file", file])).code, 1);
  const exported = await run(["profiles", "export", "local-secrets"]); assert.match(exported.stdout, /apiVersion: pyro\/v1/);
  const profile = preview.profile;
  const createdProfile = (await json(["profiles", "create", "--data", JSON.stringify({ ...profile, name: "CLI test profile" })])).profile;
  assert.equal(createdProfile.id, "cli-test-profile");
  const changed = (await json(["profiles", "update", createdProfile.id, "--data", JSON.stringify({ ...createdProfile, description: "Updated from CLI" })])).profile;
  assert.equal(changed.description, "Updated from CLI");
  assert.equal((await run(["profiles", "delete", createdProfile.id])).code, 0);
  const rule = { id: "cli-rule", name: "Test rule", enabled: true, scope: "all_text", match: "contains", pattern: "cli-private-marker", action: "block", risk: 1 };
  const app = (await json(["apps", "create", "--name", "CLI app", "--default-profile-id", "local-secrets", "--local-rules", JSON.stringify([rule])])).app;
  const appKey = await json(["keys", "create", "--name", "CLI key", "--app-id", app.id]);
  assert.ok(appKey.key.startsWith("pf_"));
  assert.ok((await json(["apps", "list"])).apps.some((item: { id: string; activeKeyCount: number }) => item.id === app.id && item.activeKeyCount === 1));
  const decision = await json(["classify", "cli-private-marker", "--labels", '{"tenant":"cli-test"}'], undefined, appKey.key);
  assert.equal(decision.action, "block"); assert.equal(decision.provider, "local-rules");
  const activity = await json(["activity", "list", "--app-id", app.id, "--label-key", "tenant", "--label-value", "cli-test"]);
  assert.equal(activity.total, 1); assert.equal(activity.events[0].id, decision.id);
  assert.equal((await json(["activity", "get", decision.id])).event.id, decision.id);
  assert.match((await run(["activity", "list", "--app-id", app.id, "--format", "csv"])).stdout, /cli-test/);
  const job = await json(["jobs", "create", "cli-private-marker"], undefined, appKey.key);
  assert.equal((await json(["jobs", "get", job.id], undefined, appKey.key)).id, job.id);
  assert.equal((await json(["playground", "hello", "--profile", "local-secrets"])).action, "allow");
  const webhook = await json(["webhooks", "create", "--name", "CLI hook", "--url", "http://127.0.0.1:1/events", "--allow-private-network", "true", "--enabled", "false", "--app-ids", JSON.stringify([app.id])]);
  assert.equal(webhook.signingSecret.length, 64);
  assert.equal((await json(["webhooks", "list"])).integrations[0].name, "CLI hook");
  assert.notEqual((await json(["webhooks", "rotate-secret", webhook.integration.id])).signingSecret, webhook.signingSecret);
  assert.equal((await run(["webhooks", "delete", webhook.integration.id])).code, 0);
  const provider = (await json(["settings", "provider", "get"])).settings;
  assert.equal((await json(["settings", "provider", "update", "--data", JSON.stringify({ ...provider, mode: "mock" })])).settings.mode, "mock");
  assert.equal((await json(["usage", "--range", "24h", "--app-id", app.id])).range, "24h");
  assert.equal((await json(["overview"])).gateway.status, "ok");
  assert.equal((await run(["apps", "delete", app.id])).code, 1);
  await json(["keys", "revoke", appKey.record.id]);
  assert.equal((await run(["classify", "hello"], undefined, appKey.key)).code, 3);
  assert.equal((await run(["apps", "delete", app.id])).code, 0);
  await json(["auth", "logout"]);
  assert.equal((await run(["profiles", "list"])).code, 3);
  assert.deepEqual(JSON.parse(await readFile(config, "utf8")).sessions, {});
});
